version: "3"

services:

  tto:
    build:
      context: "./"
    container_name: "tto"
    image: tto:0.1
    restart: always
    volumes:
      - /etc/tto/conf.json:/etc/tto/conf.json
      - /opt/tto:/opt/tto

